/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package server;

import java.io.BufferedReader;
import java.io.InputStreamReader;

import org.glassfish.tyrus.server.Server;

public class App {
    public static void main(final String[] args) {
        new Thread(() -> {
            System.out.print("Starting server.../n");
            runServer();
        }).start();
    }

    public static void runServer() {
        Server server = new Server(
            DiscoveryEndpoint.class,
            ConnectionAcceptEndpoint.class, 
            ConnectionRequestEndpoint.class
        );
        
        try {
            server.start();
            final BufferedReader reader = new BufferedReader(new InputStreamReader(System.in));
            System.out.print("Please press a key to stop the server.");
            reader.readLine();
        } catch (final Exception e) {
            throw new RuntimeException(e);
        } finally {
            server.stop();
        }
    }
}
